In [1]:
!pip install joblib

In [2]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
import pandas as pd

plt.style.use("fivethirtyeight")

In [3]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None): #eta is the learning rate, epochs is the no. of iterations(default value is None)
        self.weights = np.random.randn(3) * 1e-4 #initialise the weights to be small as convergence is faster 
        self.eta = eta # learning rate
        self.epochs = epochs # iterations
        
    def _z_outcome(self, inputs, weights): #Private method (convention used in python)
        return np.dot(inputs, weights) #multiply inputs with the corresponding weights 
    
    def activation_function(self, z):
        return np.where(z > 0, 1, 0) #if z > 0 put as 1,otherwise 0
        
    def fit(self, X, y):#X independent variable and y is the dependent variable
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))] #X-matrix with bias. 
        #np.c_ concatenation of matrixes with the 4x1 matrix of -1s
        print(f"X with bias: \n{X_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch >> {epoch + 1}")
            print("--"*10) #We do early stopping of epochs if the errors are 0 using if-else condition(we don't want to use unnecessary computing resources)
            
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f"predicted value after forward pass: \n{y_hat}")
            
            self.error = self.y - y_hat
            print(f"error: \n{self.error}")
            
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)
            print(f"updated weights after epoch: {epoch + 1}/{self.epochs}: \n{self.weights}")
            print(f"##"*10)
            
            
    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(X), 1))] #define X with bias matrix again
        z = self._z_outcome(X_with_bias, self.weights) #self.weights are the updated weights
        return self.activation_function(z)

In [4]:
OR = {       #OR gate
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,1,1,1]
}

df_OR = pd.DataFrame(OR)

df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [5]:
def prepare_data(df, target_col="y"):
    X = df.drop(target_col, axis=1)
    y = df[target_col]
    
    return X, y

In [6]:
X, y = prepare_data(df_OR)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [7]:
y

0    0
1    1
2    1
3    1
Name: y, dtype: int64

In [8]:
X, y = prepare_data(df_OR)

ETA = 0.1
EPOCHS = 10

model_or = Perceptron(eta=ETA, epochs=EPOCHS)

model_or.fit(X, y) #weights have converged in earlier epochs (Could have used early stopping)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[0 0 1 0]
error: 
0    0
1    1
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[ 0.10003077  0.19985857 -0.19998028]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 0.10003077  0.19985857 -0.09998028]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[1.00030773e-01 1.99858565e-01 1.97213128e-05]
####################
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3    0
Name:

In [9]:
model_or.predict(X=[[0,0]]) #prediction from the perceptron algorithm 

array([0])

In [10]:
AND = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,0,0,1]
}

df_AND = pd.DataFrame(AND)

df_AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [11]:
X, y = prepare_data(df_AND)

ETA = 0.1
EPOCHS = 10

model_and = Perceptron(eta=ETA, epochs=EPOCHS)

model_and.fit(X, y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[1 0 0 0]
error: 
0   -1
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[ 9.99387149e-02  9.96913247e-02 -5.24545162e-05]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[-6.12851205e-05 -3.08675254e-04  2.99947545e-01]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[0.09993871 0.09969132 0.19994755]
####################
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0


In [12]:
XOR = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,1,1,0]
}

df_XOR = pd.DataFrame(XOR)

df_XOR


x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [13]:
X, y = prepare_data(df_XOR)

ETA = 0.1
EPOCHS = 10

model_xor = Perceptron(eta=ETA, epochs=EPOCHS)

model_xor.fit(X, y) #No convergence of weights
#perceptron only works for linearly separable data 

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[0 1 0 1]
error: 
0    0
1    0
2    1
3   -1
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[-2.74083599e-05 -9.98263211e-02  6.52066185e-05]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 9.99725916e-02  1.73678856e-04 -1.99934793e-01]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[-2.74083599e-05 -9.98263211e-02  6.52066185e-05]
####################
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0